name: dpl
channels:
  - conda-forge
  - pytorch
dependencies:
  - pip:
    - biopython==1.79
    - black==21.10b0
    - click==8.0.4
    - einops==0.4.1
    - flake8==4.0.1
    - gdown==4.6.0
    - isort==5.10.1
    - ipympl==0.9.2
    - joblib==1.1.0
    - jupyterlab==3.4.8
    - meeko==0.4.0
    - mypy==0.910
    - numpy==1.23.3
    - pdb-tools==2.5.0
    - pysen==0.10.2
    - pytest==7.1.2
    - pytorch-lightning==1.7.7
    - scipy==1.9.3
    - torch-ema==0.3
    - torchmetrics==0.11.4
    - wandb==0.13.*
  - pytorch::pytorch=1.12.1
  - conda-forge::python=3.9
  - conda-forge::setuptools=59.5.0
  - conda-forge::cudatoolkit==11.3.1
  - conda-forge::rdkit==2021.9.4
  - conda-forge::pip
